# Generated by Django 3.2.5 on 2021-07-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('J', 'Jeans'), ('T', 'Tshirt'), ('TW', 'Top Wear'), ('BW', 'Buttom Wear')], max_length=2),
        ),
    ]
